Traceback (most recent call last):
  File "/work/courses/digital_human/6/miniconda3/envs/DART/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/courses/digital_human/6/miniconda3/envs/DART/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/courses/digital_human/6/iDART/visualize/vis_seq.py", line 414, in <module>
    vis_primitive_list(primitive_data_list, args)
  File "/work/courses/digital_human/6/iDART/visualize/vis_seq.py", line 154, in vis_primitive_list
    primitive_data = primitive_data_list[0]
IndexError: list index out of range
